"""Generate a config repository scaffold (with samples) for the `init` command."""

from __future__ import annotations

import logging
from pathlib import Path

from ghfanout.builder import BASE_DIR_NAME, COMMON_PROFILE
from ghfanout.config import (
    IGNORE_FILENAME,
    MANIFEST_FILENAME,
    OVERLAYS_DIR_NAME,
    ROOT_CONFIG_FILENAME,
)
from ghfanout.errors import ConfigError

logger = logging.getLogger(__name__)

# Placeholder filled into `org` in ghfanout.yaml when it is not specified.
PLACEHOLDER_ORG = "your-org-here"

# Sample profile name / overlay name generated by the scaffold.
EXAMPLE_PROFILE = "java-service"
EXAMPLE_OVERLAY = "example-service"

_ROOT_CONFIG_TEMPLATE = """\
# Destination GitHub org (required). overlays/<name> corresponds to the <org>/<name> repository
org: __ORG__
# Specify host only when using GitHub Enterprise Server (defaults to github.com)
# host: github.example.com
# Deployment method (defaults to pr). push pushes directly to the target branch, bypassing a PR
# deploy_mode: pr
# Output directory for build (defaults to dist). Relative paths resolve against this file's dir
# output_dir: dist
# GitHub App authentication settings. Token and private key contents (secrets) cannot be
# written in YAML; they can only be passed via environment variables
# (GHFANOUT_TOKEN / GHFANOUT_APP_PRIVATE_KEY, etc.).
# For private_key_file, a path outside this repository is recommended to avoid accidental commits
# auth:
#   app_id: 123456
#   # installation_id: 789  # resolved automatically from org if omitted
#   private_key_file: ~/.config/ghfanout/app.pem
"""

_GITIGNORE = """\
# Sample .gitignore distributed in common to every repository
*.log
.DS_Store
"""

_GHFANOUTIGNORE = """\
# .ghfanoutignore — files under base/ that ghfanout must NOT distribute.
# Same syntax as .gitignore ('#' starts a comment only at the start of a line).
# Each pattern is matched against a file's path within its profile (before any
# .jinja suffix is stripped), so a profile can keep its own README or helper
# files without shipping them. Example patterns — a README.md at any depth,
# all markdown files, everything under docs/ except docs/keep.md:
#
# README.md
# *.md
# docs/
# !docs/keep.md
"""

_POM_XML_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!-- Sample pom.xml template for ghfanout. Only files with the .jinja extension get variable
     expansion, and are distributed under the name with that extension stripped (pom.xml).
     artifactId is filled with the destination repository name, and version is filled with
     manifest.yaml's values.version (0.1.0 if unspecified) -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>{{ repo }}</artifactId>
  <version>{{ values.version | default("0.1.0") }}</version>
</project>
"""

_MANIFEST = """\
# Profiles to distribute (directory names under base/). common/ is always included
bases:
  - java-service
# Destination branches (defaults to the target repository's default branch)
# branches:
#   - main
#   # Using the object form lets you override bases or values for just that branch
#   - name: release-1.x
#     bases: [java-service-legacy]
#     # Per-branch values are deep-merged into the top-level values
#     values:
#       version: "0.9.9"
# Specify this to change the deployment method for only this repo (default: ghfanout.yaml's value)
# deploy_mode: push
# Values referenced from templates (files with the .jinja extension). The built-in variables
# repo (repository name) and org are available even without defining values
# values:
#   version: "1.2.3"
"""


def _template_files(org: str) -> dict[str, bytes]:
    """Return the "relative path -> file content" mapping to generate, in generation order."""
    return {
        ROOT_CONFIG_FILENAME: _ROOT_CONFIG_TEMPLATE.replace("__ORG__", org).encode("utf-8"),
        IGNORE_FILENAME: _GHFANOUTIGNORE.encode("utf-8"),
        f"{BASE_DIR_NAME}/{COMMON_PROFILE}/.gitignore": _GITIGNORE.encode("utf-8"),
        f"{BASE_DIR_NAME}/{EXAMPLE_PROFILE}/pom.xml.jinja": _POM_XML_TEMPLATE.encode("utf-8"),
        f"{OVERLAYS_DIR_NAME}/{EXAMPLE_OVERLAY}/{MANIFEST_FILENAME}": _MANIFEST.encode("utf-8"),
    }


def init_config_repo(target: Path, org: str | None = None) -> list[Path]:
    """Generate a config repository scaffold at target.

    Individual scaffold files that happen to already exist are skipped without
    being overwritten.

    Args:
        target: Directory to generate into.
        org: GitHub org name filled into ghfanout.yaml (a placeholder if None).

    Returns:
        Paths of the files actually created.

    Raises:
        ConfigError: If ghfanout.yaml already exists in target (the directory
            is considered already initialized).
    """
    root_config_path = target / ROOT_CONFIG_FILENAME
    if root_config_path.exists():
        raise ConfigError(
            f"{root_config_path} already exists. "
            "init cannot be run on an already-initialized directory."
        )

    created: list[Path] = []
    for rel_path, content in _template_files(org or PLACEHOLDER_ORG).items():
        dest = target / rel_path
        if dest.exists():
            logger.info("%s already exists, skipping", dest)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)
        created.append(dest)
    return created
